### ISSUE TITLE
It doesn't seem to be responsive

### ISSUE THREAD

**Issue by tvirelli** [ifightcrime/bootstrap-growl#60]
Here is what I have:

```javascript
$(document).ready(function(e) {
	$.bootstrapGrowl('My Message Goes Here. If it is long, it does not wrap on my mobile device.', {
		ele: 'body',
		type: 'danger',
		offset: {from: 'top', amount: 20},
		align: 'right',
		width: 400,
		delay: 5000,
		allow_dismiss: true,
		stackup_spacing: 10
	});
});
```

If my message is of any length, when viewing on smaller mobile phones like iPhone 5s, the message doesn't wrap, it just shoots off the screen.

I attached an example.

![growl_example](https://cloud.githubusercontent.com/assets/1253043/9152523/d4eea9ea-3df1-11e5-8f90-4ed2ff108c47.png)

**Comment by ileadu** [comment]
Ok, I got it. Thank you a lot.

Tony Virelli <notifications@github.com> 於 2015年8月9日 星期日寫道：

**Comment by tvirelli** [comment]
Nevermind. Wow, just looking back at my code showed me the error of my ways. I have a hard width set:
`width: 400,`
Once I removed that it was responsive.
