### ISSUE TITLE
github.io page needs updating

### ISSUE THREAD

**Issue by minglethepringle** [ifightcrime/bootstrap-growl#71]
Under **Available Options** the code says:
`type: 'info', // (null, 'info', 'error', 'success')`

Need to update `error` to `danger`.

**Comment by ifightcrime** [comment]
Can you send a PR? Thanks.

**Comment by minglethepringle** [comment]
@ifightcrime I can't find the HTML page to change in this repo lol

**Comment by minglethepringle** [comment]
@ifightcrime Oh, need to switch branches. Will send a PR.

**Comment by minglethepringle** [comment]
@ifightcrime Didn't see the other branch, oops. Will send a PR.
